services:
  - type: web
    name: linkedin-job-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn linkedin_scraper:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
