services:
  - type: web
    name: linkedin-job-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        value: linkedin-scraper-2025
      - key: LINKEDIN_EMAIL
        value: henryshao2020@gmail.com
      - key: LINKEDIN_PASSWORD
        value: 10shaoyan-
